### PR TITLE
provide get-struct-accessors in a submodule

### LINKED ISSUE #2: alexis/util/struct: would it make sense to provide some version of the `get-struct-accessors` helper function?
Would it make sense to provide the `get-struct-accessors` helper function, or some version of it, so that I, or someone else, could use it to define other similar macros?

### PR DESCRIPTION
**Pull request by AlexKnauth**
closes https://github.com/lexi-lambda/racket-alexis/issues/2

### CODE REVIEW

**Comment by lexi-lambda** [comment]
Looks like a bunch of CI failures... take a look at the builds and fix it up. Also, I think this should be documented, too.

**Comment by AlexKnauth** [comment]
Oops I forgot a `for-syntax`.

**Comment by AlexKnauth** [comment]
The 6.1.1 build is failing, but that's already failing on the `master` branch (but not on the `v6.1.1` branch).

**Comment by AlexKnauth** [comment]
The other builds are passing.

I'm not exactly sure what to do for docs though, and you would know more about this function than I would.

**Comment by lexi-lambda** [comment]
Yeah, the 6.1.1 build's tests are all actually passing, but running cover is hitting a submodule bug, so that's fine. Could you add some simple docs, though?

**Edit**: Whoops, missed your last comment. I'll try to write some docs for this later.

**Comment by AlexKnauth** [comment]
I'm getting the red underline in the docs, and I'm not sure why.

**Comment by AlexKnauth** [comment]
Oh. Typo in the `@defmodule[(submod alexis/utils/struct get-struct-accessors)]`, `utils` instead of `util`.

**Comment by AlexKnauth** [comment]
@lexi-lambda 
What do you think?

**Comment by lexi-lambda** [comment]
Thanks, merged.

**Comment by AlexKnauth** [comment]
Should you update the `v6.1.1` branch as well?
See https://github.com/jackfirth/lens/pull/111#issuecomment-120799927 and https://github.com/jackfirth/lens/pull/111#issuecomment-120801977

**Pull request closed without merging**
